name: Build playground
on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  run:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2

      - run: npm install -g esy

      - name: Try to restore install cache
        uses: actions/cache@v1
        with:
          path: ~/.esy/source
          key: source-${{ hashFiles('**/playground/esy.lock/index.json') }}

      - name: Install
        run: esy install
        working-directory: playground

      - name: Print esy cache
        id: print_esy_cache
        run: node .github/workflows/print_esy_cache.js

      - name: Try to restore build cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: build-${{ matrix.os }}-${{ hashFiles('**/playground/esy.lock/index.json') }}
          restore-keys: build-${{ matrix.os }}-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/playground/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: git submodule update --init && ./scripts/buildocaml.js

      - run: ./scripts/ninja.js config && ./scripts/ninja.js build

      - run: yarn # installs all bucklescript packages that we'll get cmij files for
        working-directory: playground

      - run: yarn build # get some fresh cmi and cmijs for reason-react
        working-directory: playground

      - run: ../jscomp/bin/cmij.exe -playground node_modules/reason-react/lib/ocaml
        working-directory: playground
  
      - run: ../scripts/ninja.js build -playground
        working-directory: playground
  
      - run: esy build-playground-prepublish
        working-directory: playground
  
      - run: node -e "require('./exports.js'); eval(ocaml.compile('Js.log Sys.ocaml_version').js_code);"
        working-directory: playground
  
      - run: node -e "require('./exports.js'); console.log(reason.compile('let t = ReactDOMRe.renderToElementWithId(<div />);').js_code)"
        working-directory: playground
  
      - run: rm -rf _esy esy.lock node_modules
        working-directory: playground
      
      - name: Archive npm artifacts
        uses: actions/upload-artifact@v1
        with:
          name: bs-platform-playground
          path: playground

