name: Main workflow

on:
  push:
    branches-ignore:
      - '**' # this workflow is temporarily disabled until it can be as fast as travis

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [8.x]

    runs-on: ${{ matrix.os }}

    env:
      BS_TRAVIS_CI: 1
      OCAMLRUNPARAM: b

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm test
